### ISSUE TITLE
Transport_filter parameter doesn't work

### ISSUE THREAD

**Issue by emixam3** [rc4/gophish-macro-attachment#1]
Hi,
I'm using Exim4 in Debian10.

I don't know how to use the transport_filter paramer. I've tried to fill the exim4.conf.tempate int /etc/exim4, but it doesn't work.
Can you help me with that?

Thanks!

**Comment by rc4** [comment]
(Copied response from GoPhish issue comments)

Hi @emixam3 - you should place the `transport_filter` in `exim.conf`. There should be a "transports" section (`begin transports`) - under that there is a `remote_smtp:` transport that looks like this

```
remote_smtp:
  driver = smtp
  message_size_limit = ...
  <snip>
```

Add the `transport_filter` line in there, like this: `transport_filter = "/path/to/python3 /path/to/script.py"`.

Hope that helps!
